### ISSUE TITLE
get_next_or_prev_in_order fails when ordering on a foreignKey

### ISSUE THREAD

**Issue by gregplaysguitar** [gregplaysguitar/django-baseclasses#3]
This is because it doesn't respect the foreignkey's Meta.ordering the way django's ORM does

**Comment by PortEdison** [comment]
Possibly the same issue, If I run `item.next_live()` on a mode that only has `ordering = ('sort_order', 'pub_date', )` it mixes up the order, but when I add `pk` to the end it sorts it out.

**Comment by PortEdison** [comment]
... looks like 1.0.8 has this fix :)
